version: '2'

services:
  kinesis:
    image: ghcr.io/etspaceman/kinesis-mock:0.2.3
    environment:
      - INITIALIZE_STREAMS=events:1
    ports:
      - '4567:4567'

#  kafka:
#    image: docker.io/bitnami/kafka:3.1
#    ports:
#      - "9092:9092"
#    environment:
#      - KAFKA_ENABLE_KRAFT=yes
#      - KAFKA_CFG_PROCESS_ROLES=broker,controller
#      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
#      - KAFKA_BROKER_ID=1
#      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
#      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
#      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
#      - ALLOW_PLAINTEXT_LISTENER=yes

#  pulsar:
#    image: apachepulsar/pulsar:2.8.0
#    ports:
#      - 8080:8080
#      - 6650:6650
#    environment:
#      PULSAR_MEM: " -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
#    command: bin/pulsar standalone --wipe-data