style       = defaultWithAlign
maxColumn   = 120
version = 3.8.2
assumeStandardLibraryStripMargin = true
align.stripMargin = true
runner.dialect = scala3
rewrite.scala3.convertToNewSyntax = true
rewrite.scala3.newSyntax.control = false