addSbtPlugin("com.eed3si9n"       % "sbt-assembly"         % "2.1.1")
addSbtPlugin("com.timushev.sbt"   % "sbt-updates"          % "0.6.4")
addSbtPlugin("net.virtual-void"   % "sbt-dependency-graph" % "0.10.0-RC1")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"         % "2.5.0")
addSbtPlugin("se.marcuslonnberg"  % "sbt-docker"           % "1.10.0")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"              % "0.4.4")
