addSbtPlugin("com.eed3si9n"     % "sbt-assembly"        % "2.5.0")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"         % "0.7.0")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"        % "2.6.2")
addSbtPlugin("com.github.sbt"   % "sbt-native-packager" % "1.11.7")
addSbtPlugin("com.github.sbt"   % "sbt-dynver"          % "5.1.1")
