addSbtPlugin("com.timushev.sbt" % "sbt-updates"          % "0.6.2")
addSbtPlugin("com.eed3si9n"     % "sbt-assembly"         % "1.2.0")
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.10.0-RC1")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"         % "2.4.6")
addSbtPlugin("com.github.sbt"   % "sbt-native-packager"  % "1.9.8")
