---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: metarank-api
  name: metarank-api
spec:
  ports:
    - name: http-api
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: metarank-api
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: metarank-api
spec:
  selector:
    matchLabels:
      app: metarank-api
  replicas: 1
  template:
    metadata:
      labels:
        app: metarank-api
    spec:
      containers:
        - name: api
          image: metarank/metarank:0.2.1
          resources:
            limits:
              memory: 600Mi
            requests:
              memory: 600Mi
          args:
            - inference
          env:
            - name: METARANK_SAVEPOINT_DIR
              value: "s3://<bucket>/<path>"
            - name: METARANK_MODEL
              value: "s3://<bucket>/<path>"
            - name: METARANK_CONFIG
              value: "s3://<bucket>/<path>"
            - name: METARANK_FORMAT
              value: "json"
            - name: METARANK_REDIS_HOST
              value: "<redis hostname>"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: metarank-keys
                  key: aws-key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: metarank-keys
                  key: aws-secret
          ports:
            - containerPort: 8080
              name: api
