apiVersion: v1
kind: Service
metadata:
  labels:
    app: metarank-api
  name: metarank-api
spec:
  ports:
    - name: http-api
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: metarank-api
  sessionAffinity: None
  type: ClusterIP
