apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "metarank.fullname" . }}
  labels:
    {{- include "metarank.labels" . | nindent 4 }}
data:
{{ ($.Files.Glob "metarank.conf").AsConfig | indent 2 }}
